import { NextRequest, NextResponse } from 'next/server'
import { createClient, isSupabaseConfigured } from '@/lib/supabase/server'
import { parseCursor, parseJournalSearch, parseLimit, parseVolumeCreate, toVolume } from '@/lib/journal/volumes'

const cols = 'id,title,archived_at,version,created_at,updated_at'
const failure = (s:number,c:string,m:string,id:string) => NextResponse.json({ error:{code:c,message:m},requestId:id },{status:s})
const rid=()=>crypto.randomUUID()
async function auth(id:string){ if(!isSupabaseConfigured)return {response:failure(503,'SUPABASE_UNAVAILABLE','私人卷册服务尚未配置。',id)};const supabase=createClient();const {data:{user},error}=await supabase.auth.getUser();return error||!user?{response:failure(401,'AUTH_REQUIRED','请先登录后管理卷册。',id)}:{supabase,user} }
const escape=(q:string)=>q.replace(/[\\%_(),.]/g,'\\$&')
export async function GET(request:NextRequest){const id=rid(),a=await auth(id);if('response'in a)return a.response;try{const q=parseJournalSearch(request.nextUrl.searchParams.get('q')),cursor=parseCursor(request.nextUrl.searchParams.get('cursor')),limit=parseLimit(request.nextUrl.searchParams.get('limit'));let query=a.supabase.from('journal_volumes').select(cols).eq('user_id',a.user.id).order('updated_at',{ascending:false}).order('id',{ascending:false}).limit(limit+1);if(q)query=query.ilike('title',`%${escape(q)}%`);if(cursor)query=query.or(`updated_at.lt.${cursor.createdAt},and(updated_at.eq.${cursor.createdAt},id.lt.${cursor.id})`);const {data,error}=await query;if(error)return failure(500,'VOLUMES_READ_FAILED','暂时无法读取卷册。',id);const rows=data??[];const slice=rows.slice(0,limit);const items=await Promise.all(slice.map(async row=>{const {count}=await a.supabase.from('journal_entries').select('*',{count:'exact',head:true}).eq('user_id',a.user.id).eq('volume_id',row.id).is('deleted_at',null);return toVolume(row,count??0)}));const last=items.at(-1);return NextResponse.json({items,nextCursor:rows.length>limit&&last?Buffer.from(JSON.stringify({createdAt:last.updatedAt,id:last.id})).toString('base64url'):null})}catch(e){return failure(400,'INVALID_INPUT',e instanceof Error?e.message:'请求无效。',id)}}
export async function POST(request:NextRequest){const id=rid(),a=await auth(id);if('response'in a)return a.response;try{const x=parseVolumeCreate(await request.json());const {data,error}=await a.supabase.rpc('create_volume',{p_id:x.id,p_title:x.title});if(error)return failure(error.message.includes('IDEMPOTENCY')?409:500,error.message.includes('IDEMPOTENCY')?'IDEMPOTENCY_CONFLICT':'VOLUME_CREATE_FAILED','卷册未能保存。',id);return NextResponse.json({volume:toVolume(data,0)},{status:201})}catch(e){return failure(400,'INVALID_INPUT',e instanceof Error?e.message:'请求无效。',id)}}
