'use client'
import Link from 'next/link'
import { FormEvent,useEffect,useState } from 'react'
import type { Entry,Favorite,Volume } from '@/lib/journal/contracts'
import { PrimaryButton } from '@/components/v2/shared/PrimaryButton'
import { PaperPanel } from '@/components/v2/shared/PaperPanel'
import { StatusMessage } from '@/components/v2/shared/StatusMessage'
import styles from './journal.module.css'
const id=()=>crypto.randomUUID()
export function JournalLibrary(){const [tab,setTab]=useState<'entries'|'volumes'|'favorites'>('entries'),[entries,setEntries]=useState<Entry[]>([]),[volumes,setVolumes]=useState<Volume[]>([]),[favorites,setFavorites]=useState<Favorite[]>([]),[error,setError]=useState(''),[title,setTitle]=useState(''),[loading,setLoading]=useState(true);const load=async()=>{setLoading(true);try{const [e,v,f]=await Promise.all([fetch('/api/journal/entries'),fetch('/api/journal/volumes'),fetch('/api/journal/favorites')]);if(!e.ok)throw new Error((await e.json()).error?.message);setEntries((await e.json()).items??[]);setVolumes(v.ok?(await v.json()).items??[]:[]);setFavorites(f.ok?(await f.json()).items??[]:[]);setError('')}catch(x){setError(x instanceof Error?x.message:'暂时无法读取私人内容。')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);async function create(event:FormEvent){event.preventDefault();if(!title.trim())return;const r=await fetch('/api/journal/volumes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:id(),title})});if(!r.ok){setError((await r.json()).error?.message||'卷册未能保存。');return}setTitle('');await load()}return <main className={styles.page}><PaperPanel className={styles.paper}><header className={styles.heading}><p className={styles.kicker}>我的卷册</p><h1>把每一件事，慢慢理成一卷</h1><p>记录、问道与收藏只属于你自己。</p></header><div className={styles.tabs}>{(['entries','volumes','favorites'] as const).map(x=><button key={x} onClick={()=>setTab(x)} aria-current={tab===x}>{x==='entries'?'记录':x==='volumes'?'卷册':'收藏'}</button>)}</div>{error&&<StatusMessage kind="error">{error}</StatusMessage>}{loading?<StatusMessage kind="loading">正在翻阅你的目录…</StatusMessage>:tab==='entries'?<><Link className={styles.newLink} href="/journal/new">新建心笺</Link><div className={styles.catalog}>{entries.map(e=><Link key={e.id} href={`/journal/entries/${e.id}`}><strong>{e.title||'无题心笺'}</strong><span>{e.body.slice(0,56)}{e.body.length>56?'…':''}</span><time>{new Date(e.updatedAt).toLocaleDateString('zh-CN')}</time></Link>)}{!entries.length&&<StatusMessage kind="empty">还没有心笺，先记下一句吧。</StatusMessage>}</div></>:tab==='volumes'?<><form className={styles.inlineForm} onSubmit={create}><input value={title} maxLength={60} onChange={e=>setTitle(e.target.value)} placeholder="新卷册，例如：工作去留"/><PrimaryButton type="submit">新建卷册</PrimaryButton></form><div className={styles.catalog}>{volumes.map(v=><Link key={v.id} href={`/journal/volumes/${v.id}`}><strong>{v.title}{v.archivedAt?' · 已归档':''}</strong><span>{v.entryCount} 条心笺</span><time>{new Date(v.updatedAt).toLocaleDateString('zh-CN')}</time></Link>)}{!volumes.length&&<StatusMessage kind="empty">还没有卷册；一件挂心的事，可以慢慢收进一卷。</StatusMessage>}</div></>:<div className={styles.catalog}>{favorites.map(f=><Link key={f.id} href={`/chapters/${f.chapterId}`}><strong>第 {f.chapterId} 章</strong><span>{f.excerpt.slice(0,60)}</span></Link>)}{!favorites.length&&<StatusMessage kind="empty">还没有收藏；读经时可把触动你的原文留下。</StatusMessage>}</div>}</PaperPanel></main>}
