'use client'
import { FormEvent,useCallback,useEffect,useState } from 'react'
import Link from 'next/link'
import type { TimelineItem,Volume } from '@/lib/journal/contracts'
import { PaperPanel } from '@/components/v2/shared/PaperPanel'
import { PrimaryButton } from '@/components/v2/shared/PrimaryButton'
import { StatusMessage } from '@/components/v2/shared/StatusMessage'
import styles from './journal.module.css'
export function VolumeDetail({id}:{id:string}){const [volume,setVolume]=useState<Volume|null>(null),[items,setItems]=useState<TimelineItem[]>([]),[title,setTitle]=useState(''),[error,setError]=useState('');const load=useCallback(async()=>{try{const [v,t]=await Promise.all([fetch(`/api/journal/volumes/${id}`),fetch(`/api/journal/volumes/${id}/timeline`)]);if(!v.ok)throw new Error((await v.json()).error?.message);const data=await v.json();setVolume(data.volume);setTitle(data.volume.title);setItems(t.ok?(await t.json()).items??[]:[]);void fetch('/api/journal/preferences',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({lastVolumeId:id})})}catch(e){setError(e instanceof Error?e.message:'暂时无法打开卷册。')}},[id]);useEffect(()=>{void load()},[load]);async function patch(body:{title?:string;archived?:boolean}){if(!volume)return;const r=await fetch(`/api/journal/volumes/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({version:volume.version,...body})});if(!r.ok){setError((await r.json()).error?.message||'卷册未能更新。');return}setVolume((await r.json()).volume)}async function rename(e:FormEvent){e.preventDefault();await patch({title})}return <main className={styles.page}><PaperPanel className={styles.paper}>{error&&<StatusMessage kind="error">{error}</StatusMessage>}{!volume?<StatusMessage kind="loading">正在打开卷册…</StatusMessage>:<><header className={styles.heading}><p className={styles.kicker}>一事一卷</p><h1>{volume.title}</h1><p>{volume.archivedAt?'此卷已归档，仍可阅读和移出记录。':'记录在这里按时间展开。'}</p></header><form className={styles.inlineForm} onSubmit={rename}><input value={title} maxLength={60} onChange={e=>setTitle(e.target.value)}/><PrimaryButton type="submit">改名</PrimaryButton><button type="button" onClick={()=>void patch({archived:!volume.archivedAt})}>{volume.archivedAt?'恢复卷册':'归档卷册'}</button></form><div className={styles.catalog}>{items.map(item=>item.type==='entry'?<Link key={`e-${item.id}`} href={`/journal/entries/${item.id}`}><strong>{item.entry.title||'无题心笺'}</strong><span>{item.entry.body.slice(0,70)}</span><time>{new Date(item.createdAt).toLocaleString('zh-CN')}</time></Link>:<Link key={`a-${item.id}`} href="/my-dao"><strong>问道</strong><span>{item.question}</span><time>{new Date(item.createdAt).toLocaleString('zh-CN')}</time></Link>)}{!items.length&&<StatusMessage kind="empty">这卷还没有记录。</StatusMessage>}</div></>}</PaperPanel></main>}
